---
version: '3'

volumes:
  data-badger: {}

services:
  jaeger:
    image: ${DOCKER_REGISTRY:-docker.io}/jaegertracing/all-in-one:${JAEGERTRACING_VERSION:-latest}
    container_name: jaeger
    environment:
      TZ: ${TIMEZONE:-America/New_York}
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      SPAN_STORAGE_TYPE: badger
      BADGER_EPHEMERAL: "false"
      BADGER_DIRECTORY_VALUE: /badger/data
      BADGER_DIRECTORY_KEY: /badger/key
    volumes:
      - data-badger:/badger
    ports:
      - "5778:5778/tcp"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "9411:9411/tcp"
      - "14268:14268/tcp"
      - "16686:16686/tcp"
