---
version: '3'

volumes:
  data-postgres: {}
  data-opennms: {}
  data-cassandra-01: {}

services:
  database:
    image: ${DOCKER_REGISTRY:-docker.io}/postgres:${POSTGRES_VERSION:-12}
    container_name: database
    hostname: database
    environment:
      TZ: ${TIMEZONE:-America/New_York}
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data-postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 30s
      retries: 3

  cassandra-01:
    image: ${DOCKER_REGISTRY:-docker.io}/cassandra:${CASSANDRA_VERSION:-3.11}
    container_name: cassandra-01
    hostname: cassandra-01
    environment:
      TZ: ${TIMEZONE:-America/New_York}
      CASSANDRA_CLUSTER_NAME: opennms-newts
      CASSANDRA_DC: opennms-lab
      CASSANDRA_RACK: opennms-lab-rack
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      LOCAL_JMX: false
      JMX_HOST: 127.0.0.1
    volumes:
      - data-cassandra-01:/var/lib/cassandra

  horizon:
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_ORG:-opennms}/${HORIZON_OCI:-horizon}:${ONMS_VERSION:-bleeding}
    container_name: horizon
    hostname: horizon
    depends_on: 
      - database
      - cassandra-01
    sysctls:
      net.ipv4.ping_group_range: "0 429496729"
    environment:
      TZ: ${TIMEZONE:-America/New_York}
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      OPENNMS_DBNAME: opennms
      OPENNMS_DBUSER: opennms
      OPENNMS_DBPASS: opennms
      OPENNMS_TIMESERIES_STRATEGY: newts
      OPENNMS_CASSANDRA_HOSTNAMES: cassandra-01
      OPENNMS_CASSANDRA_KEYSPACE: newts
      OPENNMS_CASSANDRA_PORT: 9042
      OPENNMS_CASSANDRA_USERNAME: cassandra
      OPENNMS_CASSANDRA_PASSWORD: cassandra
    volumes:
      - ./horizon-overlay:/opt/opennms-overlay
    command: ["-s"]
    ports:
      - "8980:8980"
      - "8101:8101"
    healthcheck:
      test: [ "CMD", "curl", "-f", "-I", "http://localhost:8980/opennms/login.jsp" ]
      interval: 1m
      timeout: 5s
      retries: 3
