---
http-url: "http://horizon:8980/opennms"
broker-url: "failover:tcp://horizon:61616"
id: "minion-lo1-1"
location: "location-1"

netmgt:
  syslog:
    syslog.listen.interface: "0.0.0.0"
    syslog.listen.port: 1514

  traps:
    trapd.listen.interface: "0.0.0.0"
    trapd.listen.port: 1162
