---
version: '3'

volumes:
  data-cassandra-01: {}

services:
  cassandra-01:
    image: ${DOCKER_REGISTRY:-docker.io}/cassandra:${CASSANDRA_VERSION:-3.11}
    container_name: cassandra-01
    hostname: cassandra-01
    environment:
      TZ: ${TIMEZONE:-America/New_York}
      CASSANDRA_CLUSTER_NAME: opennms-newts
      CASSANDRA_DC: opennms-lab
      CASSANDRA_RACK: opennms-lab-rack
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      LOCAL_JMX: 'false'
      JMX_HOST: 127.0.0.1
    volumes:
      - data-cassandra-01:/var/lib/cassandra
    ports:
      - "9042:9042/tcp"
      - "7199:7199/tcp"
