---
version: '3'
services:
  minion:
    image: opennms/minion:bleeding
    environment:
      - TZ=Europe/Berlin
      - JAVA_MIN_MEM=512M
      - JAVA_MAX_MEM=2048M
    volumes:
      - ./minion-config.yaml:/opt/minion/minion-config.yaml
    command: ["-f"]
    healthcheck:
      test: "/health.sh"
      interval: 30s
      timeout: 20s
      retries: 3
  ports:
    - "1162:1162/udp"
    - "1514:1514/udp"
    - "4729:4729/udp"
    - "8102:8102/tcp"
